name: Automate Workflow # workflow name
on:
  push:
    branches: [ main ] # trigger when push into branch main

jobs:
  unit-test:
    name: Run Unit Test # job name
    runs-on: ubuntu-latest
    steps: # run step
      -   name: Checkout Code
          uses: actions/checkout@v3
      -   name: Setup Java17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'zulu'
      -   name: Run Unit Tests
          run: ./gradlew test