name: Automate Workflow # workflow name
on:
  push:
    branches: [ main ] # trigger when push into branch main

jobs:
  linter:
    name: Run Linter # job name
    runs-on: ubuntu-latest
    steps: # run step
      -   name: Checkout Code
          uses: actions/checkout@v3
      -   name: Setup Java17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'zulu'
      -   name: Run Linter
          run: ./gradlew spotlessCheck
  unit-test:
    name: Run Unit Test
    runs-on: ubuntu-latest
    needs:
      - linter # run after linter
    steps:
      -   name: Checkout Code
          uses: actions/checkout@v3
      -   name: Setup Java17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'zulu'
      -   name: Run Unit Tests
          run: ./gradlew test
  build:
    name: Build Java
    runs-on: ubuntu-latest
    needs:
      - linter
      - unit-test
    steps:
      -   name: Checkout Code
          uses: actions/checkout@v3
      -   name: Setup Java17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'zulu'
      -   name: Build Java
          run: ./gradlew build